osx_image: xcode8
language: objective-c

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
  # Build framework Debug
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Debug -sdk iphonesimulator clean
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Debug -sdk iphonesimulator build

  # Build framework Release
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Release -sdk iphonesimulator clean
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Release -sdk iphonesimulator build

  # Build Example Debug
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginatorExample -configuration Debug -sdk iphonesimulator clean
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginatorExample -configuration Debug -sdk iphonesimulator build


