osx_image: xcode8
language: objective-c

script:
  # Build framework Debug
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Debug -sdk iphonesimulator clean
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Debug -sdk iphonesimulator build

  # Build framework Release
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Release -sdk iphonesimulator clean
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginator -configuration Release -sdk iphonesimulator build

  # Build Example Debug
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginatorExample -configuration Debug -sdk iphonesimulator clean
  - xcodebuild -project SwiftPaginator.xcodeproj -target SwiftPaginatorExample -configuration Debug -sdk iphonesimulator build


