osx_image: xcode8
language: objective-c

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
  # Build framework Debug
  - xctool clean build -project SwiftPaginator.xcodeproj -scheme SwiftPaginator -configuration Debug -sdk iphonesimulator

  # Build framework Release
  - xctool clean build -project SwiftPaginator.xcodeproj -scheme SwiftPaginator -configuration Release -sdk iphonesimulator

  # Build Example Debug
  - xctool clean build -project SwiftPaginator.xcodeproj -scheme SwiftPaginatorExample -configuration Debug -sdk iphonesimulator


